const ROLES = {
  USER: "USER",
  ADMIN: "ADMIN",
};

const USER_STATUS = {
  ACTIVE: "ACTIVE",
  BLOCKED: "BLOCKED",
};

const COMPLETION_STATUS = {
  STARTED: "STARTED",
  COMPLETED: "COMPLETED",
};

const REVIEW_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

const WITHDRAWAL_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  PAID: "PAID",
};

const UPI_VERIFICATION_STATUS = {
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
};

module.exports = {
  ROLES,
  USER_STATUS,
  COMPLETION_STATUS,
  REVIEW_STATUS,
  WITHDRAWAL_STATUS,
  UPI_VERIFICATION_STATUS,
};
